services:
  db:
    image: postgres:16.6
    container_name: sendstack-db
    environment:
      POSTGRES_USER: sendstackadmin
      POSTGRES_PASSWORD: sendstackadminpassword
      POSTGRES_DB: sendstack
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      # - ./scripts:/docker-entrypoint-initdb.d
volumes:
  db_data: